-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM ONLINE_SALE
INNER JOIN USER_INFO
ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
GROUP BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),GENDER