-- 코드를 입력하세요
SELECT DISTINCT CART_PRODUCTS.CART_ID
FROM CART_PRODUCTS 
INNER JOIN (SELECT CART_ID
            FROM CART_PRODUCTS 
            WHERE NAME = 'Yogurt') AS P
ON CART_PRODUCTS.CART_ID = P.CART_ID
WHERE NAME = 'Milk'
ORDER BY CART_ID