-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
FROM REST_INFO
INNER JOIN
(SELECT FOOD_TYPE, MAX(FAVORITES) AS MF
FROM REST_INFO
GROUP BY FOOD_TYPE) AS M
ON REST_INFO.FOOD_TYPE = M.FOOD_TYPE AND FAVORITES = MF
ORDER BY FOOD_TYPE DESC