-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID , COUNT(*) AS RECORD
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
INNER JOIN (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE>='2022-08_01' AND START_DATE <= '2022-10-31'
            GROUP BY CAR_ID
            HAVING COUNT(*)>=5) AS F
ON CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = F.CAR_ID
WHERE START_DATE>='2022-08_01' AND START_DATE <= '2022-10-31'
GROUP BY MONTH(START_DATE),CAR_ID
ORDER BY MONTH, CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID DESC




# SELECT CAR_ID
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE>='2022-08_01' AND START_DATE <= '2022-10-31'
# GROUP BY CAR_ID
# HAVING COUNT(*)>5