-- 코드를 입력하세요
SELECT FOOD_PRODUCT.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
INNER JOIN (SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
FROM FOOD_PRODUCT
GROUP BY CATEGORY) AS M
WHERE FOOD_PRODUCT.CATEGORY = M.CATEGORY 
      AND PRICE = MAX_PRICE 
      AND FOOD_PRODUCT.CATEGORY IN ('과자','김치','국','식용유')
ORDER BY MAX_PRICE DESC
