-- 코드를 입력하세요
SELECT APNT_NO,PT_NAME, APPOINTMENT.PT_NO, DOCTOR.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT
INNER JOIN DOCTOR
ON MDDR_ID = DR_ID
INNER JOIN PATIENT
ON PATIENT.PT_NO = APPOINTMENT.PT_NO
WHERE APNT_CNCL_YN = 'N' AND DOCTOR.MCDP_CD = 'CS' AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD